version: '3.1'

services:
  mongo:
    image: "mongo:4.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  mysql: # name of the third service
    network_mode: host
    build: sql # specify the directory of the Dockerfile
    ports:
      - "3306:3306" # specify port forwarding
  sftp:
    network_mode: host
    build: sftp # specify the directory of the Dockerfile
    ports:
      - "22:22" # specify port forwarding
